# config/config.yaml
camera:
  # 0 = 기본 웹캠, 또는 이미지 폴더 테스트시 null
  source: 0
  image_folder: null
  loop: false

yolo:
  # 모델 파일 경로
  #coco_weights: yolov5n.pt
  #custom_weights: C:/Users/user/OneDrive/Documents/VSCode/pi_AutoPark/yolov5/best5.pt
  coco_weights: /home/pi/autopark/yolov5n.pt
  custom_weights: /home/pi/autopark/yolov5_weight/best5.pt
  conf_thres: 0.3
  iou_thres: 0.45
  max_det: 50

monodepth:
  object_height: 0.3
  camera_height: 0.4
  tilt_angle: 0
  method: ratio

# slot_geometry에서 'slot_area_coords'를 제거하고, 주차 구역을 'detect_parking_slot_by_contour'에서 동적으로 찾도록 함

path_planner:
  path_segments: 5

general:
  lat0: 37.7749
  lon0: -122.4194
  final_approach_threshold: 0.3

avoid:
  pan_scan_angles: [30, 100]
  pan_scan_delay: 0.2
  pan_center_angle: 90

parking:
  park_tolerance: 0.05
  stop_steering_angle: 90
  final_step_size: 0.1

pid:
  p: 1.0
  i: 0.1
  d: 0.01

logging:
  level: INFO
  file: "logs/autopark_log.txt"
